### ISSUE TITLE
px-dropdown-click is not firing the event once an item is selected.

### ISSUE THREAD

**Issue by galva-ge** [PredixDev/px-dropdown#1]
HTML:

`              <px-dropdown>
                <px-dropdown-text class="px-dropdown-text">Text</px-dropdown-text>
                <px-dropdown-chevron class="px-dropdown-chevron"></px-dropdown-chevron>
                <px-dropdown-content class="px-dropdown-content" max-cont-character-width="10"
                extend-dropdown="true" extend-dropdown-by="15" items={{data}} px-dropdown-click={{downdownHandler()}}>
                </px-dropdown-content>
              </px-dropdown>`

I see the function being called during the page load. The function is called for each item in the drop down but after the page is loaded the function is not called once an item is selected.

**Comment by mdwragg** [comment]
@runn-vermel

**Comment by runn-vermel** [comment]
Hi galva-ge,

px-dropdown-click is an event that is fired whenever an item in the dropdown is clicked -  it passes the click event when it's fired.  no need to specify it as an attribute in your code.

You have to listen to this event being fired, not specify it in the tag itself. 

Please let us know if you need more clarification.
Thanks!

**Comment by YSambaiah** [comment]
Hi runn-vermel,
Could you please provide code snippet for this.

**Comment by runn-vermel** [comment]
HI @YSambaiah 
You can find all the info you need about event listeners right here: https://www.polymer-project.org/1.0/docs/devguide/events
