### ISSUE TITLE
How to set and get the value of dropdown when checkbox-mode="true"

### ISSUE THREAD

**Issue by contactrajiv08** [PredixDev/px-dropdown#10]
Hi,

I am using px-dropdown component for a multi-select dropdown. To show a multi select dropdown i have used  checkbox-mode="true" attribute of px-dropdown component, but i am not able to set or get the value of a multi select dropdown.

I tried `document.querySelector('#idofdropdown').selectedKey` to get its value but it is not giving any value except the display value that i am setting from my angular code.

Please suggest a solution.

Thank You,
Rajiv K

**Comment by benoitjchevalier** [comment]
Hello,

you can use the "items" property on the px-drodpown-content component (not the px-dropdown).

Each element in this array will have a "checked" property set to true or false, reflecting the state of the checkbox. Please note that if the initial array you pass in doesn't contain the "checked" property then it won't be added until the checkbox state has changed, so I would advise to pass an "items" array with explicit "checked" attribute set, something like that:

```
<px-dropdown display-value="Elephant">
  <px-dropdown-content id="test" checkbox-mode extend-dropdown='true' extend-dropdown-    by='25' max-cont-character-width='10' items='[{"key":"key1","val":"Iphone","checked":true},{"key":"key2","val":"Android","checked":false},{"key":"key3","val":"Blackberry","checked":true}, {"key":"key4", "val":"blah","checked":false}]'>
  </px-dropdown-content>
</px-dropdown>
```

Let me know if that helps.

**Comment by contactrajiv08** [comment]
Thanks Ben! it worked this time when i set "checked" property to the items. But still i am not able to get the checked checkbox values in my angular code. It always gives me 'false' as i set "checked": false by default in my json items.

I tried below code (just to check) to get the values in my angular code after selecting some check-boxes:

             `for (var i = 0; i < $scope.allenvDD.length; i++) {
              window.alert($scope.allenvDD[i].checked);
            }`

From inspect element in chrome i can see, when i click on any checkbox it doesn't change the "checked" property to true of false accordingly.

Thanks,
Rajiv K

**Comment by benoitjchevalier** [comment]
Hi Rajiv,

I think you might be hitting a angular/polymer binding issue here. On our demo the 'items' array reflects the checked property properly as seen [here](http://codepen.io/FrenchBen/pen/dXxyAP?editors=1001) (try accessing document.getElementById('test').items).

let me know if you can reproduce the issue in this codepen

Cheers,
Ben

**Comment by contactrajiv08** [comment]
Great! `document.getElementById('test').items` worked for me. Thank you so much Ben.
