### ISSUE TITLE
pxDropdown.dropdown_content_value_changed event fired does not contain Key property

### ISSUE THREAD

**Issue by adrian-gonzalez** [PredixDev/px-dropdown#12]
## Expected behavior and actual behavior:

We expect to catch the 'dropdown_content_value_changed' event fired from the pxDropdown element, and then retrieve the textValue and key properties from that event. The textValue is being outputted and transferred successfully, however the key always returns back as undefined. Both key and val properties are included in the Object passed to the px-dropdown-content element.

In my page, we have the following instance of pxDropdown:

`<px-dropdown id="pxDropdown" display-value="Devices">
            <px-dropdown-content  class="px-dropdown-content" max-cont-character-width="10" items="{{devices_items}}">
            </px-dropdown-content>
        </px-dropdown>`

{{devices_items}} gets altered in one of our methods and gets set to an Object. A sample value passed to it is:

`var objectToPass = [{"key":"1", "val":"One"}, {"key":"2", "val":"Two"}];`

We included the following listener to catch the event fired by the pxDropdown element whenever the dropdown value changes:

`listeners: {
                'pxDropdown.dropdown_content_value_changed': 'dropdownValChanged'
            },`

We want to then retrieve the events detail properties: key, and textValue. For our development work, we have this in our 'dropdownValChanged(evt)' method:

`console.log("value selected: " + evt.detail.textValue);
  console.log("key selected: " + evt.detail.key);`

The textValue property has the expected value. However the key property comes back as undefined.

## Environment 

component version number: px-dropdown#0.10.5
Browser: 52.0.2743.116 (64-bit)
operating system: Mac El Capitan v. 10.11.5

**Comment by benoitjchevalier** [comment]
Hello,

can you try version 0.11.0? I think this version includes the feature you're asking for!

Let me know if that solves your issue

Cheers,
Ben

**Comment by adrian-gonzalez** [comment]
Cool, updating to 0.11.0 or later resolved the issue. Thanks Ben!

Is it on the roadmap to include an "added functionality" section for the various px components found on the Predix Developer UI page?
http://predixdev.github.io/predix-ui/

**Comment by benoitjchevalier** [comment]
We're currently discussing how to communicate new features effectively but haven't come up to a conclusion yet. We realize it can be hard to find out what has been added recently!

At the moment I would advise keeping an eye on the website you mentioned, all demos should now be up to date and automatically updated when we add features/fix bugs! We're also in the process of adding a Codepen to each demo so that anyone can play with the latest version of a component.

I'll close this issue for now but contact me if you have more questions.

Cheers,
Ben
