### ISSUE TITLE
enable / disable items [enhancement]

### ISSUE THREAD

**Issue by jimdefrisco** [PredixDev/px-dropdown#13]
It would be useful to support a "disabled" boolean property for items in px-dropdown-content.

**Comment by benoitjchevalier** [comment]
Hi Jim,

can you describe what behavior you have in mind? i.e would the disabled items be hidden or greyed out or not selectable?

**Comment by jimdefrisco** [comment]
Hi Ben,
Like menu items: greyed out, not clickable. Dynamically updated (could be via method or item property update)

Let me know if you need more detail. I can also implement and open a PR if you're swamped with chart work :-)

Jim

**Comment by benoitjchevalier** [comment]
Hey Jim,

still happy to bring that in if you have a PR for it ;)

**Comment by jimdefrisco** [comment]
thanks Ben :-)  
Been sick, and working through other things. It's on my list.

**Comment by jimdefrisco** [comment]
Just opened a PR for the feature - let me know if there is something more I need to add.

**Comment by benoitjchevalier** [comment]
Just merged it - thanks for your work!

**Comment by benoitjchevalier** [comment]
Implemented in 2.2.0
