### ISSUE TITLE
Feature Request : KeyBoard/Keys integration 

### ISSUE THREAD

**Issue by akshayjk** [PredixDev/px-dropdown#16]
As the title suggests, this is a feature request. Since there is no other place I found to include the feature request, I am putting it here, If there is more appropriate place for the same, please guide me there.
1. We are using the px dropdown for displaying countries and states. For some countries, there is huge list of states/counties. Instead of scrolling through the long list of states/counties. it is more intuitive to hit keyboard key to go to that county (e.g.  for choosing 'Maharashtra' State in states list of India, one needs to scroll till 'M', instead if user hits key "m" on keyboard, it would scroll down till the first state starts with "m", sounds more intuitive.).
2. Also, if there is any implementation for the tab key, (possible expected behavior is once focus is onto the dropdown, the dropdown list opens and we can move through the list with up and down arrow key)

**Comment by sumeet-singh04** [comment]
👍 I support this. Will be willing to provide help in implementing this if this is an accepted feature request.

**Comment by sumeet-singh04** [comment]
Hey @randyaskin, check out this [branch](https://github.com/sumeet-singh04/px-dropdown/tree/add-keyboard-integration). i did some work on the the keyboard integration. Share if you have any comments. 

TBD: I still need to figure to hide the tooltip if the user is using keyboard to navigate the list.
