### ISSUE TITLE
_includeTooltip fails on null tooltips

### ISSUE THREAD

**Issue by JimHillGE** [PredixDev/px-dropdown#17]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:
Null this.tooltipValue causes error to be thrown

## Steps to reproduce the problem:
When using px-data-table with dropdown columns it is possible to assign:

tooltip-message="{{cellValidation.failedValidationErrorMessage}}"

it is possible for this to be null in px-data-table.

However, in general since this is a property anyone could assign it to be null if they aren't careful.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
"0.11.5"
Chrome
Windows 7.. laptop

## Code examples help us better understand the issue - follow the [CodePen](http://codepen.io/mdwragg/pen/LNwmpB) or [jsfiddle](https://jsfiddle.net/Lqmcwhw0/3/), templates, which both use polygit, to help explain the issue.

If you need to know please don't hesitate to contact me. I think the issue is fairly straightforward. I would issue pull but I am unclear what the desired handling of this would be. Return false?

**Comment by randyaskin** [comment]
New version of dropdown no longer uses tooltip.
