### ISSUE TITLE
px-dropdown does not work with ng-repeat

### ISSUE THREAD

**Issue by LeftLegAndRightLeg** [PredixDev/px-dropdown#24]
Hi guys,

px-dropdown does not like ng-repeat in AngularJS 1 framework. px-dropdown becomes un-clickable when being wrapped in ng-repeat.

we will appreciate it if you can fix that problem.

Best,
Bailiang

**Comment by runn-vermel** [comment]
hi there,

Can you please create a codepen with the problem in it?

Thanks!

**Comment by LeftLegAndRightLeg** [comment]
hi team,

  I have a codepen demo here.

  http://codepen.io/bailiang/details/GrJvKQ/

  Could you please refer to this codepen link ? 

  If you need more info or have any question, please just let me know.

Thanks,
Bailiang

**Comment by randyaskin** [comment]
I saw some chatter on the Forums related to this issue. We did try reaching out to our contacts at Google but they didn't have an immediate answer, we'll follow up today. However it looks like your CodePen stopped working? I don't see the dropdown working inside OR outside of the ng-repeat (Mac, Chrome 55) - did you change something on it?

**Comment by LeftLegAndRightLeg** [comment]
Hi , I didn't modify the dome. It seems like the a problem with polygit.org. Because other demos about px components on code pen are not working. Do you know the latest method to import polymer and px components in codePen ?  These warnings in console are fine. Thank you for the reply.

**Comment by randyaskin** [comment]
Rob @ Google says they're rebooting Polygit and reviewing a PR at the same time.

**Comment by randyaskin** [comment]
See lines 2 - 5 of [this CodePen](http://codepen.io/randyaskin/pen/pRWgNx?editors=1010) for the solution. You'll have to use `webcomponents.min.js` (instead `webcomponents-lite.min.js`) which includes the old shadow DOM polyfill for ng1/polymer1 interop, and include the global Polymer setting for shadow DOM on line 4 **before** you import polymer.html, then you should be good to go.

**Comment by mailmrmanoj** [comment]
@randyaskin  Seems the  [codepen](https://codepen.io/randyaskin/pen/pRWgNx?editors=1010) still behaves the same manner.Is there anything more to be changed to make the dropdown functional?Thanks

**Comment by randyaskin** [comment]
We use a different polygit import than we did 12 months ago. I have updated the CodePen accordingly, but I’ll remind you that you should in no way rely on CodePen or Polygit in any substantial way as anything other than a learning tool.
