### ISSUE TITLE
px-dropdown-value-changed event not firing

### ISSUE THREAD

**Issue by horologiumx** [PredixDev/px-dropdown#26]
I have a px-dropdown on my page:
`<px-dropdown display-value="abcde"><px-dropdown-content items="{{_defectDropdown}}"></px-dropdown-content></px-dropdown>`

With an event listener:
`'px-dropdown-value-changed': '_defectSelected'`

The px-dropdown-value-changed event does not propagate up however. 
I'm using px-dropdown version 2.2.0

**Comment by randyaskin** [comment]
Changed in v2.2.1 so that px-dropdown-value-changed event propagates.
