### ISSUE TITLE
not able to capture events exposed by px-dropdown

### ISSUE THREAD

**Issue by manit815** [PredixDev/px-dropdown#27]
Hi,
I am trying to integrate the px-dropdown component with Angular2. 

I am not able to capture the px-dropdown-checkbox-changed and px-dropdown-value-changed events exposed by the component.

I have been able to capture px-dropdown-click. 

My html looks like this:
<div class="pxDropdown">
  <px-dropdown [displayValue]="selectedState" >
    <px-dropdown-content checkbox-mode="true"
      [items]='items'  (px-dropdown-value-changed)="hello($event)">
    </px-dropdown-content>
  </px-dropdown>
</div>
<br>
<div><label>Selected Value: </label> <input [value]="selectedState"/></div>
<br>

The component that is using this template is:

export class PxDropdownComponent {
  title: string = 'Two way binding with Px dropdown';
  items: Object[] = [{ "key": "florida", "val": "Florida" }, { "key": "iowa", "val": "Iowa" },
    { "key": "new york", "val": "New York" }];

  selectedState: string = '';

  constructor() {
    PolymerElement('px-dropdown');
  }

  hello(evt: any){
    console.log(evt);
    //console.log(event.detail.detail.sourceEvent.currentTarget.childNodes[2]);
  }
}

Any clue on why this is not working?

**Comment by sumeet-singh04** [comment]
Hello @manit815 , I can help you in rectifying this issue. Do you have a plunker or fiddle that you can share ?

**Comment by manit815** [comment]
Hey Sumeet, So apparently I was able to figure that out and now that works. One more question which I have is, (PS: I am new to Polymer) I want to utilize iron-icon to display font awesome icons. I have modified the px-dropdown.html like this:

<template>
    <style include="px-dropdown-styles"></style>
    <style include="px-theme-styles"></style>
    <div
    on-tap="triggerClicked"
    on-mouseover="_hoverOn"
    on-mouseout="_hoverOff"
    class$="{{_dropcellClass(opened, hover)}} flex flex--middle dropcell"
    id="dropcell">
      <iron-icon icon="{{icon}}" style="padding-left: 5px"></iron-icon>
      <px-dropdown-text display-value="{{displayValue}}" max-cont-character-width="{{_maxCharWidth}}" tooltip-value={{value}}></px-dropdown-text>
      <template is="dom-if" if="{{_hideChevron(hideChevron)}}">
        <px-dropdown-chevron class="px-dropdown-chevron"></px-dropdown-chevron>
      </template>
    </div>
    <div style="position:relative;">
      <content select="px-dropdown-content"></content>
    </div>
  </template>

The thing is it serves my purpose as of now. But say the changes to the bower components will not be persisted. And if somebody else runs bower install they will not have my changes. So, how can I still utilize it? And what could be a possible way to do it?

**Comment by manit815** [comment]
<style include="px-dropdown-styles"></style>
    <style include="px-theme-styles"></style>
    <div
    on-tap="triggerClicked"
    on-mouseover="_hoverOn"
    on-mouseout="_hoverOff"
    class$="{{_dropcellClass(opened, hover)}} flex flex--middle dropcell"
    id="dropcell">
      <iron-icon icon="{{icon}}" style="padding-left: 5px"></iron-icon>
      <px-dropdown-text display-value="{{displayValue}}" max-cont-character-width="{{_maxCharWidth}}" tooltip-value={{value}}></px-dropdown-text>
      <template is="dom-if" if="{{_hideChevron(hideChevron)}}">
        <px-dropdown-chevron class="px-dropdown-chevron"></px-dropdown-chevron>
      </template>
    </div>
    <div style="position:relative;">
      <content select="px-dropdown-content"></content>
    </div>

**Comment by manit815** [comment]
so, basically a customization I am doing to get the font awesome icon.

**Comment by runn-vermel** [comment]
HI @manit815 -it seems that you'd like to add a (dynamically assigned) font awesome icon next to each entry in px-dropdown - is that correct?

either way, a few things:
1. px-theme-styles should not be inside a component
2. you should never have to edit the component. Hopefully, there's an API in the component to do what you want to do. If there isn't, feel free to write a PR and submit it to us (i would talk to use before you go through the trouble of doing that to ensure it works with our design system).
3. to ensure shadow DOM compatibility, please use px-polymer-font-awesome.

you're absolutely right that it'll get overwritten - we don't recommend doing this - also, if you decide to fork this and stay with your version, you'll need get the added benefit of bug fixes and new functionality in the original px-dropdown.

**Comment by manit815** [comment]
Hey @runn-vermel, so not exactly that.

So basically a font awesome icon to be displayed next to the drop down button text.

Fa:fa-filter-Epl(say this is the text)-chevron icon
And when user clicks a drop down appears.

I think may be in two days time I'llbe able to submit a pull request and then you can have a look.

**Comment by runn-vermel** [comment]
looking forward to it :)

**Comment by randyaskin** [comment]
Closing this based on age and the misleading title. Feel free to open another issue / PR for your followup question around adding custom icons inside the dropdown.
