### ISSUE TITLE
Checkbox bug in the demo

### ISSUE THREAD

**Issue by PiotrekPaprocki** [PredixDev/px-dropdown#28]
In the demo of [px-dropdown at predix-ui.com](https://www.predix-ui.com/#/components/px-dropdown/)  you are missing `checkbox-mode` attribute in `px-dropdown-content`, without which checkboxes are not displayed. It would be nice if you will fix it, I spent a few moments to catch it :)

Thanks

**Comment by randyaskin** [comment]
To clarify, the API/demo page for [px-dropdown-content](https://www.predix-ui.com/px-dropdown/px-dropdown/px-dropdown-content-demo.html) does contain information and a demonstration of checkbox-mode. However, it should not be appearing on the main px-dropdown demo page, as that is a bit misleading.
