### ISSUE TITLE
how to get value of selected item in px-dropdown

### ISSUE THREAD

**Issue by rmdesai** [PredixDev/px-dropdown#3]
on change of drop-down it showing selected value, but when attaching addEventListener for px-dropdown-click not getting selected value. Is there any way to get selected value in AngularJS

**Comment by benoitjchevalier** [comment]
The selected value can be retrieved in the event listener through evt.target.firstChild.textContent (evt being the parameter of your event listener).

Also you can access the selected value on the px-dropdown-content element with the "selectedValue" attribute.

Let me know if that helps you.
