### ISSUE TITLE
Feature Request: Add search input box in drodown.

### ISSUE THREAD

**Issue by sumeet-singh04** [PredixDev/px-dropdown#30]
Hi,

Our team is working with px-ui and we have a requirement to have dropdown with an input search box. The search box helps in filtering items in the dropdown.

Expected behavior:
Have a flag to toggle search box in the dropdown list and use the input in the search to filter the list items.

**Comment by randyaskin** [comment]
Have you looked at px-typeahead? What you've described is somewhat a combination of both components, but it may meet your needs: https://www.predix-ui.com/#/components/px-typeahead/

**Comment by sumeet-singh04** [comment]
@randyaskin  Yes we did look at the typeahead. We are already working with our own version of px-typeahead with enhancements. 
Anyways, it's different from typeahead coz the search box is required to be present within the list/ dropdown. We talked to UX but is seems this req was pulled out of a previous version of the product so kind of required.

**Comment by sumeet-singh04** [comment]
@randyaskin Hey Randy, do you think you guys can pull in this feature into px-dropdown, given I create a PR with the implementation ?

**Comment by randyaskin** [comment]
Added in v3.0.0.
