### ISSUE TITLE
Bug: tooltip don't hide and get misaligned while scrolling within the dropdown list. 

### ISSUE THREAD

**Issue by sumeet-singh04** [PredixDev/px-dropdown#31]
Bug:

The px-dropdown doesn't hide/ move tooltips when you have hovered over a dropdown item, and scroll within the dropdown. The tooltip shows and moves up/down as you scroll while maintaining hover in the dropdown list.

http://codepen.io/sumeet-singh04/pen/XpyJRG

![image](https://cloud.githubusercontent.com/assets/6270649/22815897/3b825dde-ef24-11e6-8ae3-5bbdba446eb4.png)

**Comment by benoitjchevalier** [comment]
Hello,

thanks for bringing this to our attention. I've fixed it in version 2.2.9, the tooltip should now hide as soon as you start scrolling.

**Comment by sumeet-singh04** [comment]
Cool. Thanks.
