### ISSUE TITLE
Multi select px-dropdown not refreshing checkboxes for item when bound data is modified

### ISSUE THREAD

**Issue by jeff-green** [PredixDev/px-dropdown#33]
## Expected behavior and actual behavior:
I'm having an issue with the px-dropdown control in multi select mode not refreshing the state of its checkboxes in the UI when the data backing the control is modified by a second control. I have a UI with a dropdown and a basic dom-repeat based list control (with remove buttons for each item) bound to the same array of items. When the bound data is modified by the list control (to set an item's checked property to false), the checkbox in the dropdown does not uncheck.

Specifically:

* When I checked one of the items in the dropdown, the change would be reflected in my list control (which filters based on item.checked == true). Unchecking in the dropdown would cause the item to be removed from my list. So, data binding and change events from dropdown -> list control are working fine.

* When I click the remove button in my list control, the item's checked property is set to false and it disappears from my list control, but the checkbox for that item in the dropdown remains checked.

Some debugger investigation showed that the bound array's data was updated correctly and that the dropdown's items collection also had the right data. We also found that the _itemsChanged function in the dom-repeat template from the dropdown was being called, which suggests that the dom-repeat does know that something changed. 

However, for whatever reason the checkbox itself is not refreshed to indicate the data has changed.

## Steps to reproduce the problem:
Should be reproduceable simply by adding a px-dropdown bound to an array of data, then adding a button that takes one of those elements and changes it's checked property. I was using dom-repeat's `event.model.set` to modify the item that was clicked, but even when going against the root's `this.set `and modifying the item in the array collection itself, the behaviour still occurred.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

Found using version 2.2.11 of the px-dropdown component in Chrome 56.0.2924.87 on Windows.

**Comment by randyaskin** [comment]
I'm able to edit the bound array on our demo page and the checkbox is checking/unchecking as expected. How are you binding the array to both your list and dropdown - Polymer or Angular or some other method?

One "gotcha" to keep in mind is that the array is expecting `checked` as a boolean and not a string, since both `"checked": "true"` and `"checked": "false"` evaluate as truthy. You'll either need `"checked": false`, or to completely remove the `checked` property from the object when it's dropped from your list component. It could be coming down to whatever binding method you're using and how it serializes booleans.

**Comment by jeff-green** [comment]
We do have a little bit of Angular in our application, but it's way up the hierarchy and both of our controls are inside the same Polymer element, so I don't think Angular would be involved.

Both controls are two way bound to a property of the Polymer element containing the key value pairs that back the dropdown/list. The array is initialized with no checked property, with the dropdown adding those properties when they are checked and my list setting them to false when they are removed via the list.

The list was setting the checked property of the element being removed to false in a click event handler using `event.model.set("item.checked", false)`.

**Comment by benoitjchevalier** [comment]
Would you be able to reproduce the issue in a codepen? It would help a lot investigating the root cause of the problem.

**Comment by randyaskin** [comment]
You may also need to use notifyPath? See https://www.polymer-project.org/1.0/docs/devguide/model-data#notify-path

**Comment by jeff-green** [comment]
So I don't mind trying to reproduce it in a codepen, but I'm not super familiar with it. I'm trying to create a polymer element that'd duplicate what I've got, but I'm not sure how to inline it (or alternatively import it from another codepen?). Any tips there?

**Comment by runn-vermel** [comment]
@jeff-green 

Go to the dropdown page on predix-ui.com and click on the pencil icon - that will open a new window with dropdown pre-configured in it.

**Comment by baontvn** [comment]
I update px-dropdown version to newest version. However, I still have the same issue. Do we have any solution for this case now? Thanks.

**Comment by jpradelle** [comment]
I have a not very nice but working fix as this is more like a workaround by adding the following code in px-dropdown-content.html file from the v3.1.1
```
    observers: [
      '_syncView(computedItems, computedItems.*)'
    ],
    _syncView: function (computedItems) {
      Array.from(this.root.querySelectorAll('#list input[type=checkbox]'))
          .forEach(function (input) {
            if (computedItems[this.$.dropdownItems.indexForElement(input)].checked !== input.checked)
              input.checked = computedItems[this.$.dropdownItems.indexForElement(input)].checked;
          }, this);
    },
```

But I don't know how to open a pull request, for a potential release v3.1.2 as the file doesn't exist anymore in master that is released under prerelease of version 4, and there is no branch for v3.

**Comment by randyaskin** [comment]
We completely rebuilt dropdown for v4, please let us know if this issue is still valid for the new version and we can reopen.
