### ISSUE TITLE
Enhancement: display selected item(s)

### ISSUE THREAD

**Issue by randyaskin** [PredixDev/px-dropdown#34]
The designers have requested the ability to visually differentiate the currently selected item in the dropdown-content box, by highlighting it with a select-blue-default background.

On a similar note, when in multi-select / checkbox mode, users have requested the ability to see something in the dropcell area to indicate that things are selected - need to decide if it should be a comma-separated list of the selected items (with truncation? and tooltip?), or simply a message like "2 selected", or something else.

**Comment by PiotrekPaprocki** [comment]
@randyaskin To second case, look at my pull-request, I've done sth similar - coma-separated list.

**Comment by randyaskin** [comment]
FIxed in v4 of the component.
