### ISSUE TITLE
px-dropdown-content is not being displayed relative to the dropdown

### ISSUE THREAD

**Issue by kunal-pandit** [PredixDev/px-dropdown#35]
## Expected behavior and actual behavior:
Expected:
When I click on the px-dropdown I should be able to see the dropdown list in the px-dropdown-content just under or above the dropdown(i.e relative to the px-dropdown).

Actual:
When I click on the px-dropdown I am not able to see the dropdown list in the px-dropdown-content just under or above it. The dropdown-content is displayed at a fixed position irrespective if the position of the px-dropdown.
sometimes it is not even visible on the page as it is being displayed out of the page bounds.

## Steps to reproduce the problem:
Include the latest px-dropdown with some other form objects like input boxes and dropdowns.
Use predix-layout-design to wrap and arrange the input items.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
component version: 2.4.4
Chrome: 53.0.2785.143
OS: OS X El captain

**Comment by randyaskin** [comment]
Fixed in v2.4.5, sorry for the mixup.

**Comment by sumeet-singh04** [comment]
@randyaskin Thanks for the quick fix.
