### ISSUE TITLE
displayValue is not changed in checkbox mode

### ISSUE THREAD

**Issue by lihongxun945** [PredixDev/px-dropdown#38]
## Expected behavior and actual behavior:
The displayed value will changed after I checked one item in checkbox mod

## Steps to reproduce the problem:
check/uncheck any item in dropdown menu

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Mac OSX 10.11.6
Chrome Version 56.0.2924.87 (64-bit)
Can reproduce on official site https://www.predix-ui.com/#/components/px-dropdown/

## Suggest
I read some code and find that: `px-dropdown` doesn't handle the `px-dropdown-checkbox-changed` event which is fired by `px-dropdown-content`, so the `displayValue` is not changed.

**Comment by randyaskin** [comment]
Px-dropdown-content has a property called "show-selected" - if you set it to true, the display-value will be updated with a comma-separated list of any selected items from the list. See http://codepen.io/randyaskin/pen/aJaWGr?&editors=1001 for an example.
