### ISSUE TITLE
px-dropdown display-value resets to "Select" when in checkbox mode

### ISSUE THREAD

**Issue by amitnarang28** [PredixDev/px-dropdown#40]
## Expected behavior and actual behavior:
Currently Placeholder value is hardcoded to **Select** word, where as there should be an option to provide place holder value so that it can say something else , e.g ALL, or Product lines etc. 

## Steps to reproduce the problem:
https://www.predix-ui.com/#/components/px-dropdown/

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
All

**Comment by randyaskin** [comment]
The property is called displayValue. It's only hardcoded in the demo page because it can interfere with the currently selected value when you're switching things back and forth.

http://codepen.io/randyaskin/pen/vxVJxr?&editors=1001

**Comment by amitnarang28** [comment]
displayValue get's overridden with the value as Select. I have done local implementation and tested it and it fails.

**Comment by randyaskin** [comment]
Sorry you're right, I wasn't in checkbox-mode. Introduced by a pull request, I'll take a look.

**Comment by leebickmtu** [comment]
Even for single select mode this would be a nice feature. So if we set 'selectedKey = null' it would clear the selection and return to the placeholder text.

**Comment by randyaskin** [comment]
I'm actually working on a complete rebuild of px-dropdown, leveraging iron-dropdown and iron-selector from Google, simplifying the API (removing px-dropdown-content and putting all the properties on the parent), etc. Obviously it will be a major version bump and we probably won't release it until the rest of the design refresh items, but I'm hoping it will fix a lot of issues people have with the current dropdown.

**Comment by PiotrekPaprocki** [comment]
So create a property to customize displayValue is a thing right now or you're waiting with any changes till the new px-dropdown is released? i might find some uses cases in my project for such property and I can create a p-r.

**Comment by randyaskin** [comment]
The property exists already, and works fine except in the specific situation described above (checkbox-mode after items are selected and deselected). I've mostly finished rebuilding the component from the ground up, I just need to re-add unit tests and figure out how to release it without breaking everything else in the system. 😜

**Comment by randyaskin** [comment]
Fixed in v4 of the component.
