### ISSUE TITLE
height issue or Gap between dropdown options and dropdown

### ISSUE THREAD

**Issue by satishpoul** [PredixDev/px-dropdown#42]
Hi,

I am using this component with search-mode="true" . filter is working properly.
![11](https://cloud.githubusercontent.com/assets/3095213/24755418/c0deb1cc-1af7-11e7-94a3-b06367a06556.jpg)

if there is not enough space below dropdown to show an items, options are showing above to the dropcell. But in the same case if i enter value to filter i am facing following issues for dropdown-items as shown below.
![13](https://cloud.githubusercontent.com/assets/3095213/24755201/e32645ca-1af6-11e7-95b4-9ccc562c4be2.jpg) ![12](https://cloud.githubusercontent.com/assets/3095213/24755202/e326e232-1af6-11e7-8894-1d0d3a8dcd35.jpg)

**Comment by randyaskin** [comment]
I noticed this and looked in to fixing it - I think it would take a lot of extra logic to dynamically calculate the height offset based on the number of results at any given point in time so I left it alone as a fringe case for now.

**Comment by randyaskin** [comment]
I think I inadvertently fixed this another way in v4.3.1 yesterday.
