### ISSUE TITLE
Version update required with API change ?

### ISSUE THREAD

**Issue by jimdefrisco** [PredixDev/px-dropdown#43]
Hi,

Our current code is pulling in v4.0.0, but it looks like a PR was merged yesterday that changes the API to remove dependency on px-dropdown-content. Sadly, our code still uses px-dropdown-content, so things are broken  :-)

We'll update our code to use the new API, but a major version change might be in order.

Jim

**Comment by benoitjchevalier** [comment]
Hey Jim,

v4.0.0 is still in prerelease and will include the redesign + the API break. You probably still should be using v3.0.0 at the moment, any reason you're pulling 4?

**Comment by jimdefrisco** [comment]
Ah, good to know. I'm not sure why we upgraded - I will ask around.  Thanks for the quick response.

**Comment by jimdefrisco** [comment]
Found the culprit - they will be appropriately flogged ;-)   Closing this issue.
