### ISSUE TITLE
px-dropdown ui issue: User is not able to search the desired ouput on click of spacebar in px-dropdown search box

### ISSUE THREAD

**Issue by nishashetty999** [PredixDev/px-dropdown#53]
**px-dropdown ui issue: User is not able to search the desired ouput on click of spacebar in px-dropdown search box**

Expected behavior and actual behavior:
Expected: When we have a list of values in dropdown list, the user should be able to search the value which has a space(Eg.: "Windows Phone") i.e. when the user enter a space in the dropdown search box, the dropdown list should filter.

Actual: When we have a list of values in dropdown list, the user is not able to search the value which has a space(Eg.: "Windows Phone") i.e. when the user enter a space in the dropdown search box, the dropdown list closes.

Steps to reproduce the problem:
- Open a dropdown which has multiple values
- Try to search a value which has a space(Eg."Windows Phone") in the dropdown search box
- The dropdown box closes

Environment (_component version number, Browser (including version), operating system, hardware, etc_): Windows 7, Chrome Browser.

**Comment by randyaskin** [comment]
Will be fixed when v4 is released in July.
