### ISSUE TITLE
Search Mode on Dropdown not working

### ISSUE THREAD

**Issue by nataliebeden** [PredixDev/px-dropdown#54]
# Submit an Issue

The code I have used to try and set up the dropdown with checkbox-mode and search-mode enabled is attached.
<img width="823" alt="screen shot 2017-06-30 at 11 11 51 am" src="https://user-images.githubusercontent.com/29238854/27748638-0617a242-5d85-11e7-8c5d-24350211a868.png">

**Comment by randyaskin** [comment]
Both checkbox-mode and search-mode are actually properties of px-dropdown-content, you don't need them on the parent component (a weird artifact of our demo page causes them to appear there). That being said, that won't _hurt_ anything. Your code looks correct to me and works fine on my local and on CodePen: https://codepen.io/randyaskin/pen/awYbOB?&editors=1001
