### ISSUE TITLE
Auto right positioning is off

### ISSUE THREAD

**Issue by benoitjchevalier** [PredixDev/px-dropdown#55]
## Expected behavior and actual behavior:

auto positioning the dropdown on the right is off, it is too much on the right:

![screen shot 2017-07-28 at 3 03 23 pm](https://user-images.githubusercontent.com/3206342/28738107-770844f2-73a6-11e7-981f-4a1debaf1431.png)

## Steps to reproduce the problem:
open devtools and pin them to the bottom so they prevent the dropdown from fully opening. Dropdown will be moved to the right, but too far

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

chrome 59

**Comment by randyaskin** [comment]
This is a very odd edge case that Kate noticed as well. When there's room, it pops below. When there's not room, it pops above. In certain very specific cases where it doesn't find room above *or* below, it pops to the right with this weird offset.

**Comment by randyaskin** [comment]
Fixed in 4.5.0 by turning off `no-overlap` in iron-dropdown and figuring out offset dynamically instead. Should only pop above or below now.
