### ISSUE TITLE
Marking items as initially selected is broken when items are replaced (multi-select mode)

### ISSUE THREAD

**Issue by davidrleonard** [PredixDev/px-dropdown#58]
# Submit an Issue

Here's a codepen that summarizes the problem well with text and the broken code example: https://codepen.io/davidleonard/pen/boqqXG?editors=1011

## Expected behavior:

1. Some items are initially passed into a `multi` select px-dropdown. The items are marked with `"selected" : "true`.
2. The items should be selected the dropdown is first opened 👍 
3. The dropdown is closed
4. Some new items are passed into the same px-dropdown. The items are marked with `"selected": "true"`.
5. The new items should be selected when the dropdown re-opened 👎 

## Actual behavior:

1-4 above are still the same. But 5 fails, and nothing is selected when the dropdown is re-opened.

1. When initial items are passed into a `multi` select px-dropdown, and some items have `selected:true` properties, the items will be marked as selected when the dropdown is opened

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

* Chrome 62
* Mac OS X El Capitan

## Hmm... 🤔 

I think the issue is here: https://github.com/PredixDev/px-dropdown/blob/056043d13f399a6ab8e503796cb597c198e2d3e4/px-dropdown.html#L461

When items are changed, the observer `_itemsChanged()` is triggered:

https://github.com/PredixDev/px-dropdown/blob/056043d13f399a6ab8e503796cb597c198e2d3e4/px-dropdown.html#L221-L228

And `_itemsChanged()` calls `_updateSelection()`:

https://github.com/PredixDev/px-dropdown/blob/056043d13f399a6ab8e503796cb597c198e2d3e4/px-dropdown.html#L445-L454

But `_updateSelection()` only updates the selection if there are no currently `selectedValues`, which there are. But they're the old ones. 

https://github.com/PredixDev/px-dropdown/blob/056043d13f399a6ab8e503796cb597c198e2d3e4/px-dropdown.html#L460-L478

I would pull this out, or just flush the `selectedValues` at the top of `_updateSelection()` but I am worried that would have unintended consequences that could break the component for existing customers (e.g. if they update the items, not replace it, should we retain `selectedValues`).

@randyaskin think you'll know better than I.

**Comment by randyaskin** [comment]
Fixed in v4.0.12.
