### ISSUE TITLE
How to get the "key" value of the selected item in the dropdown? 

### ISSUE THREAD

**Issue by vasanthid** [PredixDev/px-dropdown#6]
When we use,

<px-dropdown display-value="Blackberry" list='[{"key":"one","val":"Iphone"},{"key":"two","val":"Android"},{"key":"three","val":"Blackberry"},{"key":"four","val":"Windows Phone"}]'></px-dropdown>

"Blackberry" is selected in the px-dropdown.
How I get the "key" value "three" of the selected item?

**Comment by benoitjchevalier** [comment]
I have added the 'selectedKey' attribute on px-dropdown, which will reflect the key of the selected element, the demo has been updated accordingly.

Let me know if that solves your issue

**Comment by vasanthid** [comment]
Thank you very much for your quick response. Truly appreciate it.

I tested the fix with new px-dropdown (v0.11.0)... and still have issues accessing "selectedKey".

selectedKey always returns "".

I have an array with key/val pairs. 

var linesArray = 

[{key:"1", val:"1"},
{key:"2", val:"2"},
{key:"3", val:"3"}
]

I have set this array to "items" attribute of "px-dropdown-content"

<px-dropdown id="lineDropdown"  
      display-value="{{lineDropdownValue}}" 
      value="{{lineDropdownValue}}">
          <px-dropdown-content extend-dropdown="true" 
                     extend-dropdown-by="25"     
                    items='{{linesArray}}'>
          </px-dropdown-content>
</px-dropdown>

Initially,  lineDropdownValue  is set to linesArray[0].val.

When I access 

document.querySelector('#lineDropdown').selectedKey

it returns "".

I am able to access "value" and "displayValue" properties.

Could you please look into this and suggest some solution?  We have 3 or 4 dropdowns on our page and we can't implement them unless this issue is fixed.

Appreciate your help.

**Comment by benoitjchevalier** [comment]
Hello,

selectedKey has a similar initial behavior to value/displayValue. This might not be optimal but at the moment the selected key has to be initialized in a similar way value/displayValue is. 

Can you try setting "selectedKey" (on px-dropdown) initially to linesArray[0].key?

selectedKey should then be updated every time someone select a new value in the dropdown.

Please let me know if that works

Cheers,
Ben

**Comment by vasanthid** [comment]
Thanks, Ben.

It works if I initially set "selectedKey" on px-dropdown. 

Then, whenever the dropdown value is changed,  I have to add "eventListener" on "change" event to execute code based on the new selectedKey.

     var elLineDropdown = document.querySelector('#lineDropdown');

      elLineDropdown.addEventListener('change', function() {
           // some custom code goes here
      });

Thank you very much.

**Comment by benoitjchevalier** [comment]
Great! If you bind a variable to selectedKey you should also be able to run code when the value changes.

I'm going to close this now, let me know if you need anything else
