### ISSUE TITLE
Expanded dropdown options floats as page scrolls

### ISSUE THREAD

**Issue by arcpato** [PredixDev/px-dropdown#60]
The multi-select and iconic dropdown menu items float on the page as you scroll to another section of the demo. 

![screen shot 2017-10-09 at 1 42 07 pm](https://user-images.githubusercontent.com/6137443/31357752-e4a38974-acf7-11e7-804f-87956033ec8d.png)

**Comment by randyaskin** [comment]
Weird. This may be a limitation of Google's iron-dropdown, which has a complicated scroll manager that's supposed to prevent this from happening. If I use two-finger scrolling on the demo page, nothing happens, but if I click or click'n'drag in the scrollbar itself, the page does scroll around the dropdown. Need to do more testing / investigation.

**Comment by randyaskin** [comment]
The Polymer team has merged a PR that fixes this behavior so that the px-dropdown content scrolls along with the rest of the page as expected. I've rebuilt predix-ui.com to pick up the change and verified the fix. Let us know if you see other odd behavior.
