### ISSUE TITLE
opening px-dropdown breaking the scroll in the page

### ISSUE THREAD

**Issue by Priyanka1403** [PredixDev/px-dropdown#61]
# When we open a dropdown, scrollbar in a page does not work.

 Steps to reproduce the problem:

## dropdown selection/open should not break other functionalities in a page.

**Comment by benoitjchevalier** [comment]
see dropdown API - allowOutsideScroll
https://www.predix-ui.com/#/elements/px-dropdown:property-allowOutsideScroll

**Comment by mailmrmanoj** [comment]
+1

**Comment by mailmrmanoj** [comment]
Seems the issue still exists.Any fix for the same in net release ?
![image](https://user-images.githubusercontent.com/7077567/32938021-cbbf8940-cba0-11e7-9579-d2387432b4b0.png)
