### ISSUE TITLE
px-dropdown issue after upgrading to version 4.0.0

### ISSUE THREAD

**Issue by ge-kosc** [PredixDev/px-dropdown#62]
px-dropdown does not work when link to web-animations in line 7 is included, when I comment out that line everything works fine. Are there any known solutions to that issue? Thanks in advance for support.

![web-animations-error](https://user-images.githubusercontent.com/32872500/31666337-22b80dac-b34c-11e7-911c-f1aa1f1e0c82.png)

**Comment by randyaskin** [comment]
I have not seen this before and can't replicate in any of our testing environments. Can you please provide the information requested in the issue template - browser, OS, steps to replicate (is it on page load or after some action), etc?

**Comment by ge-kosc** [comment]
Thanks for response, my OS is windows 7 professional used with Chrome Version 61.0.3163.100 (Official Build) (64-bit). The issue arises on initial page load. When `web-animations-next-lite.min.html` is replaced with `web-animations.min.html` an issue disappears following https://github.com/PredixDev/px-app-nav/issues/29

**Comment by randyaskin** [comment]
Interesting. I wasn't involved in that discussion. Updated the import in v4.0.15.

**Comment by randyaskin** [comment]
Actually, now that I know what that import is ( 😄 ), we're not actually using neon-animation in dropdown anymore, it must be leftover from an older iteration. Removed completely in v4.0.16.
