### ISSUE TITLE
'display-value-changed' event is not emitted and displayValue does not notify

### ISSUE THREAD

**Issue by ge-kosc** [PredixDev/px-dropdown#63]
Hi,

## Expected behavior and actual behavior:

'display-value-changed' event is not emitted and displayValue does not notify

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

"version": "4.0.16",
operating system: Windows 7,
browser: Chrome Version 62.0.3202.62 (Official Build) (64-bit)

**Comment by benoitjchevalier** [comment]
Works as expected, this property is the placeholder text. You're probably looking for `selected` or `selectedItems`: https://www.predix-ui.com/#/elements/px-dropdown
