### ISSUE TITLE
Listening to `px-dropdown-selection-changed` events in the same page while using multiple px-dropdowns

### ISSUE THREAD

**Issue by mailmrmanoj** [PredixDev/px-dropdown#65]
I'm using `px-dropdown` in my angular 4 project and using the below code to listen to selection changes.I'm able to get the selected value but if I use multiple 'px-dropdown' in the same page how can I listen to each separately is the concern.

JS:

` document.addEventListener('px-dropdown-selection-changed', function (evt: any) { 
            const selectedData = evt.detail.key; 
        });`

HTML:

` <px-dropdown id="sensor-selection"  items='[{"key":"All Data Sources","val":"All Data Sources"},{"key":"Item1","val":"Box Model"},    {"key":"Item2","val":"Circle Model"},{"key":"Item3","val":"Triangle Model"}]' button-style="tertiary" selected="All Data Sources"></px-dropdown>`

If I add another `px-dropdown` in the same page with different selection criteria  it also listens to the same event listener and triggers actions that are related to the previous dropdown and performs functions associated to that.
Please let me know how can I achieve it as I find no difrentiators in `px-dropdown-selection-changed` events while using multiple `px-dropdowns`

**Comment by randyaskin** [comment]
Answered on the forum:
https://forum.predix.io/questions/29812/listening-to-multiple-px-dropdown-selection-change.html
