### ISSUE TITLE
No Localization Support

### ISSUE THREAD

**Issue by LRagji** [PredixDev/px-dropdown#68]
# Doesn't implement Polymer.AppLocalizeBehavior for localization

Like other components px-dropdown doesn't support localization showing multi selected values in english 'x selected'
## Steps to reproduce the problem:
Put the component in a localized app..

**Comment by randyaskin** [comment]
Added in v4.3.0. This component is a bit non-standard in that we have the `displayValue` property, but I don't know if it's worth issuing a new major version and breaking the API just to standardize the way the string is handled, so leaving it for now.
