### ISSUE TITLE
Icon size styling property not working

### ISSUE THREAD

**Issue by TheWillG** [PredixDev/px-dropdown#70]
I have noticed that the "--px-dropdown-icon-size" property does not scale the px-dropdown icon when using an iconic menu.  I am going to submit a PR that I believe will fix this problem.

**Comment by randyaskin** [comment]
Fixed in v4.4.1. Also had to change the height a bit so the menu doesn't overlap the button - may still need additional tweaking to introduce some padding or something, depending on the size you're using. Let me know if that works.

**Comment by TheWillG** [comment]
You sure are quick haha.  Please disregard my PR since it is essentially exactly what you have done here.  Thanks.
