### ISSUE TITLE
Can you help adding mouse out auto close support

### ISSUE THREAD

**Issue by gengivan** [PredixDev/px-dropdown#80]
Hi,

Current dropdown component, after user clicks the dropdown then shows the options, but it does not auto close when mouse out, user has to click on other place to close.

Right now we have an use case, using dropdown as kabob menu which is dynamically rendered when hover. So when user clicks on the menu, options get displayed, then user mouse out which triggers both the kabob and options hidden.  When user mouse over again, it just directly display the kabob and options without clicking which is not user friendly.

So can you help adding an option that support auto close the options after mouse out?

Thanks,
Ivan Geng

**Comment by randyaskin** [comment]
I don't think this is feasible to implement in the component itself, as it is specific to your use case and not the way that standard dropdowns or menus operate. 

Whatever code you are using to hide the kebab on mouseout should either call the `toggle()` method of px-dropdown, or set `opened` to false.
