### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by seanbischoff** [PredixDev/px-dropdown#9]
After today's checkins the Demo dropdown (index.html) does not seem to work.

1 Go to http://predixdev.github.io/predix-ui/?show=px-dropdown&type=component
2 Click on "Elephant" dropdown
Expected: Menu opens, left and lower value/tag html indicators change.
Actual: a line appears - a collapsed empty menu? nothing changes.

**Comment by runn-vermel** [comment]
Hi @seanbischoff,

Thanks for the heads up - i fixed the demo :)
